teummeireo/ProfessorTooFast

.classpath, .settings/org.eclipse.core.resources.prefs, src/main/webapp/css/styles.css, src/main/webapp/error.jsp, src/main/webapp/login.jsp, src/main/webapp/main.jsp, src/main/webapp/my_survey.jsp, src/main/webapp/register.jsp, src/main/webapp/statistics.jsp, src/main/webapp/survey.jsp
=> Feature/#4 feat 설문 jsp 구현

.gitignore, build/classes/mydb.properties
=> [add] #34 삭제 완료.

src/main/webapp/main.jsp
closed #32 
---
Main 기본 틀 만들었습니다.
=> [feat] #32 Main 기초 작업

.settings/org.eclipse.wst.common.component, build/classes/mydb.properties, src/main/webapp/check_admin.jsp, src/main/webapp/check_session.jsp, src/main/webapp/check_user.jsp, src/main/webapp/main.jsp, src/main/webapp/my_survey.jsp, src/main/webapp/statistics.jsp, src/main/webapp/survey.jsp
=> [feat] #39 check 구현 완료.

src/main/webapp/css/login_register.css, src/main/webapp/login.jsp, src/main/webapp/register.jsp
=> [feat] #44 로그인 비밀번호 복구완료

src/main/webapp/statistics.jsp
closed #42 
- 관리자 페이지 (백엔드 연결된)기능 구현
#TODO
- 코드 정리, 예외처리
- 하루 통계 게이지 적용
=> [feat] #42 관리자 페이지 백엔드 연결 1차 구현

src/main/webapp/css/main_css.css, src/main/webapp/login.jsp, src/main/webapp/main.jsp, src/main/webapp/my_survey.jsp, src/main/webapp/survey.jsp
=> [feat] #46 로그인 로그아웃 활성 비활성화

.classpath, .settings/org.eclipse.wst.common.component, resources/fileupload.properties, resources/mydb.properties, src/main/webapp/register.jsp
=> [fix] #67 회원가입 오류수정

resources/fileupload.properties, resources/mydb.properties
=> [chore] #77 resources 폴더 삭제 완료

Dockerfile
=> [mod] #79 dockerfile 수정완료

src/main/webapp/css/statistics_admin.css, src/main/webapp/statistics_admin.jsp
closed #75 
- 통계 페이지 전체인원 미반영 버그 수정
- 기간 통계 모달 게이지바에 통계 수치 표기로 수정
=> Refactor/#75 설문 통계페이지 리팩토링

.gitignore, Dockerfile, build/classes/mypostgre.properties, src/main/resources/mypostgre.properties
=> [merge] #87 mypostgre.properties 삭제 및 이그노어

src/main/webapp/css/login_register.css
=> [UI] #92 회원가입 폼 수정

src/main/webapp/css/main_css.css, src/main/webapp/css/style.css, src/main/webapp/main.jsp
closed #91 
---
main에 닉네임 추가, 토마토 범위 늘리기
=> [feat] #91 main에 닉네임 추가

.classpath, .settings/org.eclipse.wst.common.component, src/main/webapp/css/my_survey_css.css, src/main/webapp/css/statistics_admin.css, src/main/webapp/my_survey.jsp, src/main/webapp/statistics_admin.jsp
=> [add] #95 css 수정

src/main/webapp/css/style.css, src/main/webapp/my_survey.jsp
closed #98
---
close-button 클릭 시 모달 닫기
=> [add] #98 close-button 클릭 시 모달 닫기

src/main/webapp/survey.jsp
=> [fix] #103 modal 해결

src/main/webapp/css/my_survey_css.css
closed #105 
---
my survey 버튼 배경 삭제
=> [fix] #105 버튼 배경 삭제

src/main/webapp/css/statistics_admin.css, src/main/webapp/my_survey.jsp, src/main/webapp/statistics_admin.jsp
=> Refactor/#111 자잘한 코드 수정

src/main/webapp/css/statistics_admin.css, src/main/webapp/statistics_admin.jsp
closed #114
---
일부만 완성했는데 뒤를 부탁합니다아....
=> [mod] #114 일별 통계 모달창 일부 수정

.gitignore, src/main/webapp/main.jsp, src/main/webapp/statistics_admin.jsp
=> [feat] #118 develop(oracle)버전 커밋

src/main/webapp/statistics_admin.jsp
=> [feat] #118 오늘 날짜 버그 진짜 수정완료.
